name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v1
      with:
          login-server: alextestacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      # Build and push the Docker image
    - name: Build and push Docker image
      uses: azure/docker@v1
      with:
          context: .
          dockerfile: Dockerfile
          image: alextestacr.azurecr.io/test/22
